### ISSUE TITLE
Freezer und Abstürze auf mobilem Browser

### ISSUE THREAD

**Issue by DGK110** [RaBa64/OpenDTU-Database#11]
### What happened?

Hallo.
Auf dem Smartphone mit mobilen Browser gibt es nach wenigen Sekunden Freezer und Abstürze.
Dazu ist auf dem Smartphone die Anzeige der Jahresübersicht Fehlerhaft.
Nur wenige Monate sichtbar.
Auf dem Chromebook oder PC gibt es diese genannten Probleme nicht.

### To Reproduce Bug

Siehe Bilder

### Expected Behavior

Danke im voraus

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

23.8.8

### Relevant log/trace output

```Shell
Habe ich nicht.
```

### Anything else?

![inbound5788746705451250567](https://github.com/RaBa64/OpenDTU-Database/assets/142320596/b8830675-7786-4f9d-b3b5-1074281efb79)
![inbound8172120469955316450](https://github.com/RaBa64/OpenDTU-Database/assets/142320596/90ba189a-071a-4580-bfb0-e89c5eda1a9c)
![inbound7410140519733206282](https://github.com/RaBa64/OpenDTU-Database/assets/142320596/5236f118-59d2-4037-a9d2-b63e6b791e36)

**Comment by danny1605** [comment]
I can only confirm this problem. hope there will be a solution.

**Comment by DGK110** [comment]
Ebenso kann man die Database.bin zwar sichern, aber es gibt keine Möglichkeit die Database.bin wieder zurück einzuspielen.

**Comment by daytona80** [comment]
same issue as described

**Comment by kinichahau2023** [comment]
confirm same Bug on Samsung Android mobile: the calendar is not adjusting his graphic size / too big and months beyond February are not visible and/or calender ist not movable left<->right
![Screenshot_20230911_183107_DuckDuckGo](https://github.com/RaBa64/OpenDTU-Database/assets/144427583/5a9043fe-b694-46e5-8400-b7a9242729c1)

Would be brilliant, if you can "repair" this problem, because the database idea is wonderful!

**Comment by RaBa64** [comment]
I am working on getting rid of the Google Charts and use some FOSS charts.
This will hopefully solve a lot of issues, especially the calender chart.

**Comment by danny1605** [comment]
The update did not fix the problem.

**Comment by kinichahau2023** [comment]
Can only confirm danny1605, described problems (bugs?) are the same as before - unfortunately.
Also "database.bin" still can be saved (good!), but not restored back.

**Comment by RaBa64** [comment]
calendar plugin has been changed
