### ISSUE TITLE
[Request] move inverters list under charts

### ISSUE THREAD

**Issue by nonflammable** [RaBa64/OpenDTU-Database#12]
### Describe the solution you'd like

![IMG_20230907_122851~2](https://github.com/RaBa64/OpenDTU-Database/assets/6041490/6c9df3f7-2655-40a0-a8e8-6baa8fbddb5d)

**Comment by daytona80** [comment]
sounds good

**Comment by RaBa64** [comment]
That should be easy, I will add that to the next release.

**Comment by RaBa64** [comment]
Please check if this release is fixing your issue:
[https://github.com/RaBa64/OpenDTU-Database/releases/tag/v23.9.13-Database](https://github.com/RaBa64/OpenDTU-Database/releases/tag/v23.9.13-Database)

**Comment by nonflammable** [comment]
> Please check if this release is fixing your issue: https://github.com/RaBa64/OpenDTU-Database/releases/tag/v23.9.13-Database

Fixed. Thank you :)
