### ISSUE TITLE
Added fullscreen diagram to display included or not?

### ISSUE THREAD

**Issue by kinichahau2023** [RaBa64/OpenDTU-Database#21]
### Is your feature request related to a problem? Please describe.

can not find where to select full screen graphic.

### Describe the solution you'd like

is the full screen graphic already included?

**Comment by MartinNK** [comment]
original opendtu 24.1.14 has fullscreen diagram intergrated ... have to wait for next release of opendtu database

look at [release notes](https://github.com/tbnobody/OpenDTU/releases/tag/v24.1.14)

**Comment by nonflammable** [comment]
update to 24.2.24

**Comment by kinichahau2023** [comment]
completed
