### ISSUE TITLE
Tagesertrag falsch

### ISSUE THREAD

**Issue by Mooz01** [RaBa64/OpenDTU-Database#26]
### What happened?

Am 4.5. war eine geplante Abschaltung vom Energieversorger.
Vermutlich durch die mehreren Aus - und Einschaltvorgänge wurden falsche Tagesertragswerte gespeichert.
Für den 4.5. : -1573844 und für den 5.5. 1601719 
Zum Vergleich... waren bei mir etwa 2 bis 16kWh = 2000 / 16000 normal.

### To Reproduce Bug

Wie kann ich die falschen Einträge bearbeiten/löschen?

### Expected Behavior

Am besten wäre eine Möglichkeit Tageserträge selbst zu bearbeiten.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

0ea19c3

### Anything else?

![image](https://github.com/RaBa64/OpenDTU-Database/assets/131199749/37f0635a-9528-43ee-a825-f83352271221)

**Comment by MartinNK** [comment]
Database is just a binary file, like ... date / hour / power ... and so on ... just use hex editor to delete wrong data and do an extra database backup if something went wrong.

I had some fails of power ... or I removed power by myself by mistake ... lost the complete daily data every time or only some hours of that day ...

**Comment by Mooz01** [comment]
Hey there,
Thanks for the reacting, but im not sure how i can get the database
backupbas a file...
i searched in the opendtu webaccess but found nothing to export for the
Database file or else...
Do i have to connect it to the pc or so for it?
Thanks for your help.
Wishing you a great evening...

MartinNK ***@***.***> schrieb am Di., 28. Mai 2024, 09:22:

**Comment by RaBa64** [comment]
For exporting the database, goto "Einstellungen/Konfigurationsverwaltung".
At "Sicherung der Konfigurationsdatei" chose "database.bin".

**Comment by RaBa64** [comment]
I got the data from the original OpenDTU software, which got it from the Hoymiles inverter.
Looks like this could be a bug in the Hoymiles inverter software.

**Comment by RaBa64** [comment]
I got the data from the original OpenDTU software, which got it from the Hoymiles inverter.
Looks like this could be a bug in the Hoymiles inverter software.
