### ISSUE TITLE
Seit Update auf v24.6.18 mehrmals täglich "Time Calibration"

### ISSUE THREAD

**Issue by XpertXXL** [RaBa64/OpenDTU-Database#29]
### What happened?

In der Ereignisanzeige tauchen mehrmals täglich "Time Calibration" Einträge auf. Der WR (Hoymiles HMS-2000-4T) startet dann neu. 

### To Reproduce Bug

nach Downgrade auf v24.5.27 läuft das Ganze wieder stabil wie gewohnt

### Expected Behavior

Wiederherstellung der Stabilität im aktuellen Image

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.6.18 

### Anything else?

Der Fehler wurde durch mehrere User (FB Gruppe) bestätigt

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by RaBa64** [comment]
Da dieser Teil der Software mit dem original OpenDTU übereinstimmt, ist der Fehler wahrscheinlich dort.
Ich mache eine aktualisierte Version, dann kannst Du prüfen, ob der Fehler weg ist.

**Comment by RaBa64** [comment]
needs to be fixed in the original OpenDTU software.

**Comment by XpertXXL** [comment]
habe ich mir fast gedacht, danke für den schnellen Support
XpertXXL
