### ISSUE TITLE
[Request] Start week on Mondays

### ISSUE THREAD

**Issue by ituri** [RaBa64/OpenDTU-Database#3]
### Is your feature request related to a problem? Please describe.

Looking at [the screenshot](https://github.com/RaBa64/OpenDTU-Database/blob/Database/docs/screenshots/23_Database.png?raw=true), it seems that in the yearly view the week starts on Sundays. 

### Describe the solution you'd like

I'd like 
* the week to start on Mondays or 
* have a setting to choose between Mondays/Sundays

**Comment by RaBa64** [comment]
I have not found a way to configure this in Google Charts.
I am currently working on using another chart library.
This will also solve this problem.

**Comment by RaBa64** [comment]
The calendar component cannot be configured for this feature.
