### ISSUE TITLE
Database Error on first start

### ISSUE THREAD

**Issue by Sn0w3y** [RaBa64/OpenDTU-Database#5]
### What happened?

My Database shows -42 yesterday and 42 kWh today.
Actually i can not reproduce the Bug..
Maybe we should dig deeper into it
![Screenshot_20230715_204650_Chrome](https://github.com/RaBa64/OpenDTU-Database/assets/4571966/38b42411-ad4f-48a3-ba82-6f42aa53d910)

### To Reproduce Bug

Not repdoducable

### Expected Behavior

Real Values

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

recent version

**Comment by RaBa64** [comment]
I will have a look.

**Comment by RaBa64** [comment]
How does it look now? Is everything normal now?

**Comment by Sn0w3y** [comment]
Did you change something?

**Comment by RaBa64** [comment]
If it still doesnt show a normal chart, please poste the content of your database from this link: http://[your_device_name_here]/api/database

**Comment by danny1605** [comment]
> If it still doesnt show a normal chart, please poste the content of your database from this link: http://[your_device_name_here]/api/database

**Comment by RaBa64** [comment]
That looks good, just let it run for a whole day and you will see the chart of the day.

**Comment by danny1605** [comment]
> That looks good, just let it run for a whole day and you will see the chart of the day.

yes everything is correct works after 1 day perfect. is the software version of the database version the same as the opentdu version? it shows in the opendtu that I'm not using the latest version.

**Comment by Sn0w3y** [comment]
> > That looks good, just let it run for a whole day and you will see the chart of the day.
> 
> yes everything is correct works after 1 day perfect. is the software version of the database version the same as the opentdu version? it shows in the opendtu that I'm not using the latest version.

How would it be if you ask such questions in PM or DM - as you saw this was a Issue Request and not a Chat :D

**Comment by kinichahau2023** [comment]
Hi Ralf, 
I still have (eventuell after >24 h) a Fanny Start value inside the graphit of the database.
Could you please helpdesk me how to remove this First (wrong, summary?) value.
See attached Screenshot.
thx in advance
![Screenshot_20230912_184554_DuckDuckGo](https://github.com/RaBa64/OpenDTU-Database/assets/144427583/14d690d6-89d1-46c1-9b9b-2ba8f27d636d)

**Comment by kinichahau2023** [comment]
sorry for the crazy type correction...
Trust you understand what was the meaning

**Comment by kinichahau2023** [comment]
Matter solved ! 
After 26h running the bar-graphic is top ok!

Remains only the unusable calender...
Maybe you can make it movable/scrollable like the Firmware-Info-Window which I can move left and right to see what is on the further right end.

rgds and thx for your nice product!

**Comment by RaBa64** [comment]
I will add a fix for this in the next release.

**Comment by RaBa64** [comment]
Please check if this release is fixing your issue:
[https://github.com/RaBa64/OpenDTU-Database/releases/tag/v23.9.13-Database](https://github.com/RaBa64/OpenDTU-Database/releases/tag/v23.9.13-Database)

**Comment by nonflammable** [comment]
Yesterday was reboot, today is something wrong.
![Zrzut ekranu 2023-10-13 094823](https://github.com/RaBa64/OpenDTU-Database/assets/6041490/48f79b96-bfff-44f7-bbb2-831e281602ae)

**Comment by RaBa64** [comment]
Has somebody else experienced this problem lately?
